---
- hosts: dev
  become: True
  tasks:
    - name: Install python3 pip
      yum:
        name: python3-pip
        state: present
   
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: newrepo
        image: "mandal44/newrepo:2.0.0.1"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
